### ISSUE TITLE
What about `Deno.connectTls` ?

### ISSUE THREAD

**Issue by justinmchase** [rclarey/socks5#2]
Connect is great but what about `connectTls`? Can that work too?

**Comment by rclarey** [comment]
It would work if you had a proxy server that supports TLS connections, but using `Deno.connectTls` would only encrypt data between the client and the proxy server. Between the proxy and the target server the data would be unencrypted. Not sure if there is a use case for this.

From what I can tell, if you want to encrypt data between the client and the target server that is done outside the SOCKS protocol. In the case of this library that would mean reimplementing the TLS protocol on top of `Deno.connect` which I think is a bad idea.

FYI my use case when writing this library was running some program (SSH, Wireguard, etc) locally that exposes a SOCKS interface. Since the SOCKS server is running locally it doesn't matter at all that TLS is not used.

**Comment by justinmchase** [comment]
I'm trying to connect to a kafka server, I'm trying to use a socks proxy to access it but no luck so far. I have this working for the database but for some reason can't get it to work for kafka. 

The kafka client is using `Deno.connectTls` but simply setting `HTTP_PROXY` or `HTTPS_PROXY` seems to not be sufficient. So I tried this library to replace the `socketFactory` maybe I'll just try doing the non tls connection...

**Comment by rclarey** [comment]
> I have this working for the database but for some reason can't get it to work for kafka.

Ah, it seems like the database probably accepts plain TCP connections but Kafka expects TCP + TLS. Unfortunately this is the use case that would require either Deno adding support for TCP proxies (then this library is no longer needed), or reimplementing TLS in this library.

> maybe I'll just try doing the non tls connection...

That should work with the current state of this library 🤞

**Comment by justinmchase** [comment]
The connection is established but it seems to just close instantly, I couldn't figure it out. Going to try a different approach. Thanks for the help.
